import { Badge, Section, Table } from "@/components/ui";
import { componentInventory, variantInventory } from "@/lib/fashion-data";

export default function InsightsPage() {
  const deadStock = variantInventory.filter((item) => item.lastSoldDays >= 60);
  const fastMovers = [...variantInventory].sort((a, b) => b.velocity30d - a.velocity30d).slice(0, 3);
  const reorder = componentInventory.filter((item) => item.stock <= item.reorderPoint);
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-ink">Insights & Forecasting</h1><p className="mt-1 text-sm text-slate-500">Spot dead stock, fast-moving categories, and components that need reorder before assembly slows down.</p></div><div className="grid gap-4 md:grid-cols-3"><Section title="Dead Stock Alerts"><div className="space-y-3">{deadStock.map((item) => <div key={item.sku} className="rounded-md border border-rose-100 bg-rose-50 p-3"><Badge tone="red">{item.lastSoldDays} days</Badge><p className="mt-2 font-medium text-ink">{item.designName}</p><p className="text-xs text-slate-600">{item.finish} / {item.size}</p></div>)}</div></Section><Section title="Fast Movers"><div className="space-y-3">{fastMovers.map((item) => <div key={item.sku} className="rounded-md border border-emerald-100 bg-emerald-50 p-3"><Badge tone="green">{item.velocity30d}/30d</Badge><p className="mt-2 font-medium text-ink">{item.category}</p><p className="text-xs text-slate-600">{item.designName}</p></div>)}</div></Section><Section title="Reorder Components"><div className="space-y-3">{reorder.map((item) => <div key={item.code} className="rounded-md border border-amber-100 bg-amber-50 p-3"><Badge tone="gold">Reorder</Badge><p className="mt-2 font-medium text-ink">{item.name}</p><p className="text-xs text-slate-600">{item.stock} / reorder {item.reorderPoint}</p></div>)}</div></Section></div><Section title="Velocity Report"><Table headers={["SKU", "Category", "Finish", "Stock", "Reserved", "Last Sold", "Velocity", "Recommendation"]}>{variantInventory.map((item) => <tr key={item.sku}><td className="px-3 py-3 font-mono text-xs">{item.sku}</td><td className="px-3 py-3">{item.category}</td><td className="px-3 py-3">{item.finish}</td><td className="px-3 py-3">{item.stock}</td><td className="px-3 py-3">{item.reserved}</td><td className="px-3 py-3">{item.lastSoldDays} days ago</td><td className="px-3 py-3">{item.velocity30d}</td><td className="px-3 py-3">{item.lastSoldDays >= 60 ? "Liquidate / discount" : item.stock <= item.reorderPoint ? "Reorder" : "Maintain"}</td></tr>)}</Table></Section></div>;
}
